// src/data.js

export const productsData = [
  {
    slug: 'web-development',
    icon: 'fas fa-laptop-code',
    title: 'Web App Development',
    description: 'Pengembangan sistem informasi, ERP mini, dan dashboard interaktif yang disesuaikan dengan proses bisnis Anda.',
    output: 'Repo + Deploy + Dokumen',
    duration: '6–12 minggu',
    cost: 'mulai dari Rp —',
  },
  {
    slug: 'mobile-development',
    icon: 'fas fa-mobile-alt',
    title: 'Mobile App (Android/iOS)',
    description: 'Aplikasi cross-platform modern menggunakan Flutter atau React Native untuk menjangkau semua pengguna.',
    output: 'APK/IPA + Backend',
    duration: '8–14 minggu',
    cost: 'mulai dari Rp —',
  },
  {
    slug: 'data-analytics',
    icon: 'fas fa-chart-bar',
    title: 'Data Analytics & BI',
    description: 'Proses ETL (Extract, Transform, Load), pembuatan dashboard KPI, dan implementasi model prediksi dasar.',
    output: 'Pipeline + Dashboard',
    duration: '4–8 minggu',
    cost: 'mulai dari Rp —',
  },
  {
    slug: 'computer-vision',
    icon: 'fas fa-eye',
    title: 'Computer Vision / NLP',
    description: 'Implementasi solusi AI untuk deteksi wajah/objek, Optical Character Recognition (OCR), dan pengembangan chatbot.',
    output: 'Model + API + UI',
    duration: '6–12 minggu',
    cost: 'mulai dari Rp —',
  },
  {
    slug: 'iot-prototype',
    icon: 'fas fa-microchip',
    title: 'Prototype IoT',
    description: 'Pengembangan perangkat Internet of Things dari level sensor, gateway, hingga komputasi tepi (edge computing).',
    output: 'Skematik + Firmware + App',
    duration: '6–10 minggu',
    cost: 'mulai dari Rp —',
  },
  {
    slug: 'cloud-devops',
    icon: 'fas fa-cloud-upload-alt',
    title: 'Cloud & DevOps',
    description: 'Layanan migrasi cloud, hardening server, CI/CD, containerization, dan monitoring infrastruktur.',
    output: 'Pipeline + Playbook',
    duration: '3–6 minggu',
    cost: 'mulai dari Rp —',
  },
  {
    slug: 'cybersecurity',
    icon: 'fas fa-shield-alt',
    title: 'Security Assessment',
    description: 'Vulnerability Assessment & Penetration Testing (VA/PT) tingkat dasar beserta laporan dan rencana remediasi.',
    output: 'Laporan + Remediation plan',
    duration: '2–4 minggu',
    cost: 'mulai dari Rp —',
  },
  {
    slug: 'ui-ux',
    icon: 'fas fa-drafting-compass',
    title: 'UI/UX Design',
    description: 'Perancangan wireframe, high-fidelity design menggunakan Figma, pembuatan design system, dan usability testing.',
    output: 'Figma + Guide',
    duration: '2–4 minggu',
    cost: 'mulai dari Rp —',
  },
];